### ISSUE TITLE
Playground should load the proto definition linked in the API Entity

### ISSUE THREAD

**Issue by OrkoHunter** [zalopay-oss/backstage-grpc-playground#12]
We have an API entity in the Catalog where the proto file is linked.

```
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: jokes-service-grpc-api
  description: gRPC API for Jokes Service
spec:
  type: grpc
  lifecycle: staging
  system: sdtk-jokes-service
  owner: sdtk_usergroup
  definition:

    $text: https://github.com/datarobot/service-registry/tree/main/services/jokes-service/dr_protobuf/jokes/service/v1/jokes.proto
```

When we open the definition of that API, this playground shows up. However it asks the user to upload the proto file again.

![Screenshot 2024-07-18 at 10 31 31 PM](https://github.com/user-attachments/assets/f6355715-5c66-430a-8f87-af1d47078e6d)

Is this the expected behavior? Ideally the playground for the particular API should load with the proto definitions already attached in the API entity. That would be the ideally user experience.

@fr0stf0x @whatvn Curious what your thoughts are on this. Also do share what would it take to build this feature, we can try to contribute. 🙏
