### ISSUE TITLE
Generate markdown doc with protoc-gen-doc and display on UI

### ISSUE THREAD

**Issue by fr0stf0x** [zalopay-oss/backstage-grpc-playground#3]
Feature request:

Generate markdown doc with protoc-gen-doc and display on UI

**Comment by costap** [comment]
Hi, trying to give this a try but still can't figure out what I'm missing to get the docs generation working, I installed the plugin and the playground look good, but missing the docs generation. I have added the below in app-config.yaml, is anything else required that I might be missing? 
```
grpcPlayground:
  document:
    enabled: true
    protocGenDoc:
      install: true
    useCache:
      enabled: true
```
